# Generated by Django 4.2.2 on 2023-06-15 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город')),
                ('description', models.TextField(verbose_name='Описание города')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название туристической компании')),
                ('image', models.ImageField(upload_to='excursions/', verbose_name='Фото (логотип) компании')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Туристическая компания',
                'verbose_name_plural': 'Туристические компании',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название экскурсии')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('children_age', models.PositiveIntegerField(blank=True, help_text='Количество лет', null=True, validators=[django.core.validators.MaxValueValidator(17, 'Максимальный возраст ребенка 17.')], verbose_name='Ограничение возраста детей')),
                ('price_children', models.PositiveIntegerField(verbose_name='Стоимость для ребенка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('gathering_place', models.CharField(help_text='Адрес и координаты(для отображения точки на карте)', max_length=32, verbose_name='Место сбора')),
                ('type_excursion', models.CharField(choices=[('PRS', 'Частная'), ('GRP', 'Групповая')], default='GRP', max_length=3, verbose_name='Тип экскурсии')),
                ('transport', models.CharField(choices=[('AVT', 'Автомобиль'), ('WLK', 'Пешая')], default='AVT', max_length=3, verbose_name='Транспорт')),
                ('size_group', models.CharField(max_length=32, verbose_name='Размер группы')),
                ('starting_point', models.CharField(max_length=64, verbose_name='Точка старта')),
                ('author', models.ForeignKey(help_text='Пользователь, добавивший экскурсию', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('categories', models.ManyToManyField(related_name='excursions', to='excursions.category', verbose_name='Категории')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='excursions.city', verbose_name='Город (локация, направление)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='excursions.company', verbose_name='Туристическая компания')),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название (номер) дня')),
                ('locations', models.CharField(max_length=128, verbose_name='Локации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Программа по дням экскурсии',
                'verbose_name_plural': 'Программы по дням экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionNotIncludePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Оплачивается отдельно', max_length=128, verbose_name='Услуга')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_included_in_price', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Не включено в стоимость экскурсии',
                'verbose_name_plural': 'Не включено в стоимость экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionIncludePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(help_text='Включено в стоимость экскурсии', max_length=128, verbose_name='Услуга')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_price', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Включено в стоимость экскурсии',
                'verbose_name_plural': 'Включено в стоимость экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='excursions/', verbose_name='Фото экскурсии')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Фото экскурсий',
                'verbose_name_plural': 'Фото экскурсий',
            },
        ),
    ]
