# Generated by Django 4.2.2 on 2023-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AddField(
            model_name='excursion',
            name='duration',
            field=models.CharField(default='12 часов', max_length=64, verbose_name='Длительность экскурсии'),
            preserve_default=False,
        ),
    ]
