# Generated by Django 4.2.2 on 2023-06-17 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_alter_category_options_alter_excursion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('ip', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('text', models.TextField(verbose_name='Текст (описание) отзыва')),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка экскурсии')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
