# Generated by Django 4.2.2 on 2023-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Отобран модератором'),
        ),
    ]
