# Generated by Django 4.2.2 on 2023-07-02 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_review_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('phone_number', models.CharField(help_text='Номер телефона должен быть в формате +7(xxx)xxx-xx-xx', max_length=17, validators=[django.core.validators.RegexValidator('^(\\+7\\([0-9]{3}\\)[0-9]{3}-[0-9]{2}-[0-9]{2})$', message='Номер телефона должен быть в формате +7(xxx)xxx-xx-xx')], verbose_name='Номер телефона')),
                ('number_people', models.PositiveIntegerField(help_text='Количество взрослых', verbose_name='Взрослые')),
                ('number_children', models.PositiveIntegerField(blank=True, help_text='Количество детей', null=True, verbose_name='Дети')),
                ('date', models.DateField(help_text='Желаемая дата', verbose_name='Дата')),
                ('comment', models.CharField(max_length=256, verbose_name='Комментарий')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование экскурсии',
                'verbose_name_plural': 'Заявки на бронирование экскурсии',
            },
        ),
    ]
