# Generated by Django 4.2.2 on 2023-07-03 19:58

from django.db import migrations, models
import excursions.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0005_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(help_text='Желаемая дата', validators=[excursions.models.date_validator], verbose_name='Дата'),
        ),
    ]
